# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jacob/Projects/C++/test/P6

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jacob/Projects/C++/test/P6

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jacob/Projects/C++/test/P6/CMakeFiles /home/jacob/Projects/C++/test/P6/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jacob/Projects/C++/test/P6/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named p6

# Build rule for target.
p6: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 p6
.PHONY : p6

# fast build rule for target.
p6/fast:
	$(MAKE) -f CMakeFiles/p6.dir/build.make CMakeFiles/p6.dir/build
.PHONY : p6/fast

src/common/byte_buffer.o: src/common/byte_buffer.cpp.o
.PHONY : src/common/byte_buffer.o

# target to build an object file
src/common/byte_buffer.cpp.o:
	$(MAKE) -f CMakeFiles/p6.dir/build.make CMakeFiles/p6.dir/src/common/byte_buffer.cpp.o
.PHONY : src/common/byte_buffer.cpp.o

src/common/byte_buffer.i: src/common/byte_buffer.cpp.i
.PHONY : src/common/byte_buffer.i

# target to preprocess a source file
src/common/byte_buffer.cpp.i:
	$(MAKE) -f CMakeFiles/p6.dir/build.make CMakeFiles/p6.dir/src/common/byte_buffer.cpp.i
.PHONY : src/common/byte_buffer.cpp.i

src/common/byte_buffer.s: src/common/byte_buffer.cpp.s
.PHONY : src/common/byte_buffer.s

# target to generate assembly for a file
src/common/byte_buffer.cpp.s:
	$(MAKE) -f CMakeFiles/p6.dir/build.make CMakeFiles/p6.dir/src/common/byte_buffer.cpp.s
.PHONY : src/common/byte_buffer.cpp.s

src/common/errors.o: src/common/errors.cpp.o
.PHONY : src/common/errors.o

# target to build an object file
src/common/errors.cpp.o:
	$(MAKE) -f CMakeFiles/p6.dir/build.make CMakeFiles/p6.dir/src/common/errors.cpp.o
.PHONY : src/common/errors.cpp.o

src/common/errors.i: src/common/errors.cpp.i
.PHONY : src/common/errors.i

# target to preprocess a source file
src/common/errors.cpp.i:
	$(MAKE) -f CMakeFiles/p6.dir/build.make CMakeFiles/p6.dir/src/common/errors.cpp.i
.PHONY : src/common/errors.cpp.i

src/common/errors.s: src/common/errors.cpp.s
.PHONY : src/common/errors.s

# target to generate assembly for a file
src/common/errors.cpp.s:
	$(MAKE) -f CMakeFiles/p6.dir/build.make CMakeFiles/p6.dir/src/common/errors.cpp.s
.PHONY : src/common/errors.cpp.s

src/common/utils.o: src/common/utils.cpp.o
.PHONY : src/common/utils.o

# target to build an object file
src/common/utils.cpp.o:
	$(MAKE) -f CMakeFiles/p6.dir/build.make CMakeFiles/p6.dir/src/common/utils.cpp.o
.PHONY : src/common/utils.cpp.o

src/common/utils.i: src/common/utils.cpp.i
.PHONY : src/common/utils.i

# target to preprocess a source file
src/common/utils.cpp.i:
	$(MAKE) -f CMakeFiles/p6.dir/build.make CMakeFiles/p6.dir/src/common/utils.cpp.i
.PHONY : src/common/utils.cpp.i

src/common/utils.s: src/common/utils.cpp.s
.PHONY : src/common/utils.s

# target to generate assembly for a file
src/common/utils.cpp.s:
	$(MAKE) -f CMakeFiles/p6.dir/build.make CMakeFiles/p6.dir/src/common/utils.cpp.s
.PHONY : src/common/utils.cpp.s

src/compiler/assign.o: src/compiler/assign.cpp.o
.PHONY : src/compiler/assign.o

# target to build an object file
src/compiler/assign.cpp.o:
	$(MAKE) -f CMakeFiles/p6.dir/build.make CMakeFiles/p6.dir/src/compiler/assign.cpp.o
.PHONY : src/compiler/assign.cpp.o

src/compiler/assign.i: src/compiler/assign.cpp.i
.PHONY : src/compiler/assign.i

# target to preprocess a source file
src/compiler/assign.cpp.i:
	$(MAKE) -f CMakeFiles/p6.dir/build.make CMakeFiles/p6.dir/src/compiler/assign.cpp.i
.PHONY : src/compiler/assign.cpp.i

src/compiler/assign.s: src/compiler/assign.cpp.s
.PHONY : src/compiler/assign.s

# target to generate assembly for a file
src/compiler/assign.cpp.s:
	$(MAKE) -f CMakeFiles/p6.dir/build.make CMakeFiles/p6.dir/src/compiler/assign.cpp.s
.PHONY : src/compiler/assign.cpp.s

src/compiler/codegen.o: src/compiler/codegen.cpp.o
.PHONY : src/compiler/codegen.o

# target to build an object file
src/compiler/codegen.cpp.o:
	$(MAKE) -f CMakeFiles/p6.dir/build.make CMakeFiles/p6.dir/src/compiler/codegen.cpp.o
.PHONY : src/compiler/codegen.cpp.o

src/compiler/codegen.i: src/compiler/codegen.cpp.i
.PHONY : src/compiler/codegen.i

# target to preprocess a source file
src/compiler/codegen.cpp.i:
	$(MAKE) -f CMakeFiles/p6.dir/build.make CMakeFiles/p6.dir/src/compiler/codegen.cpp.i
.PHONY : src/compiler/codegen.cpp.i

src/compiler/codegen.s: src/compiler/codegen.cpp.s
.PHONY : src/compiler/codegen.s

# target to generate assembly for a file
src/compiler/codegen.cpp.s:
	$(MAKE) -f CMakeFiles/p6.dir/build.make CMakeFiles/p6.dir/src/compiler/codegen.cpp.s
.PHONY : src/compiler/codegen.cpp.s

src/compiler/compiler.o: src/compiler/compiler.cpp.o
.PHONY : src/compiler/compiler.o

# target to build an object file
src/compiler/compiler.cpp.o:
	$(MAKE) -f CMakeFiles/p6.dir/build.make CMakeFiles/p6.dir/src/compiler/compiler.cpp.o
.PHONY : src/compiler/compiler.cpp.o

src/compiler/compiler.i: src/compiler/compiler.cpp.i
.PHONY : src/compiler/compiler.i

# target to preprocess a source file
src/compiler/compiler.cpp.i:
	$(MAKE) -f CMakeFiles/p6.dir/build.make CMakeFiles/p6.dir/src/compiler/compiler.cpp.i
.PHONY : src/compiler/compiler.cpp.i

src/compiler/compiler.s: src/compiler/compiler.cpp.s
.PHONY : src/compiler/compiler.s

# target to generate assembly for a file
src/compiler/compiler.cpp.s:
	$(MAKE) -f CMakeFiles/p6.dir/build.make CMakeFiles/p6.dir/src/compiler/compiler.cpp.s
.PHONY : src/compiler/compiler.cpp.s

src/compiler/expr.o: src/compiler/expr.cpp.o
.PHONY : src/compiler/expr.o

# target to build an object file
src/compiler/expr.cpp.o:
	$(MAKE) -f CMakeFiles/p6.dir/build.make CMakeFiles/p6.dir/src/compiler/expr.cpp.o
.PHONY : src/compiler/expr.cpp.o

src/compiler/expr.i: src/compiler/expr.cpp.i
.PHONY : src/compiler/expr.i

# target to preprocess a source file
src/compiler/expr.cpp.i:
	$(MAKE) -f CMakeFiles/p6.dir/build.make CMakeFiles/p6.dir/src/compiler/expr.cpp.i
.PHONY : src/compiler/expr.cpp.i

src/compiler/expr.s: src/compiler/expr.cpp.s
.PHONY : src/compiler/expr.s

# target to generate assembly for a file
src/compiler/expr.cpp.s:
	$(MAKE) -f CMakeFiles/p6.dir/build.make CMakeFiles/p6.dir/src/compiler/expr.cpp.s
.PHONY : src/compiler/expr.cpp.s

src/compiler/frame.o: src/compiler/frame.cpp.o
.PHONY : src/compiler/frame.o

# target to build an object file
src/compiler/frame.cpp.o:
	$(MAKE) -f CMakeFiles/p6.dir/build.make CMakeFiles/p6.dir/src/compiler/frame.cpp.o
.PHONY : src/compiler/frame.cpp.o

src/compiler/frame.i: src/compiler/frame.cpp.i
.PHONY : src/compiler/frame.i

# target to preprocess a source file
src/compiler/frame.cpp.i:
	$(MAKE) -f CMakeFiles/p6.dir/build.make CMakeFiles/p6.dir/src/compiler/frame.cpp.i
.PHONY : src/compiler/frame.cpp.i

src/compiler/frame.s: src/compiler/frame.cpp.s
.PHONY : src/compiler/frame.s

# target to generate assembly for a file
src/compiler/frame.cpp.s:
	$(MAKE) -f CMakeFiles/p6.dir/build.make CMakeFiles/p6.dir/src/compiler/frame.cpp.s
.PHONY : src/compiler/frame.cpp.s

src/compiler/package.o: src/compiler/package.cpp.o
.PHONY : src/compiler/package.o

# target to build an object file
src/compiler/package.cpp.o:
	$(MAKE) -f CMakeFiles/p6.dir/build.make CMakeFiles/p6.dir/src/compiler/package.cpp.o
.PHONY : src/compiler/package.cpp.o

src/compiler/package.i: src/compiler/package.cpp.i
.PHONY : src/compiler/package.i

# target to preprocess a source file
src/compiler/package.cpp.i:
	$(MAKE) -f CMakeFiles/p6.dir/build.make CMakeFiles/p6.dir/src/compiler/package.cpp.i
.PHONY : src/compiler/package.cpp.i

src/compiler/package.s: src/compiler/package.cpp.s
.PHONY : src/compiler/package.s

# target to generate assembly for a file
src/compiler/package.cpp.s:
	$(MAKE) -f CMakeFiles/p6.dir/build.make CMakeFiles/p6.dir/src/compiler/package.cpp.s
.PHONY : src/compiler/package.cpp.s

src/compiler/stmt.o: src/compiler/stmt.cpp.o
.PHONY : src/compiler/stmt.o

# target to build an object file
src/compiler/stmt.cpp.o:
	$(MAKE) -f CMakeFiles/p6.dir/build.make CMakeFiles/p6.dir/src/compiler/stmt.cpp.o
.PHONY : src/compiler/stmt.cpp.o

src/compiler/stmt.i: src/compiler/stmt.cpp.i
.PHONY : src/compiler/stmt.i

# target to preprocess a source file
src/compiler/stmt.cpp.i:
	$(MAKE) -f CMakeFiles/p6.dir/build.make CMakeFiles/p6.dir/src/compiler/stmt.cpp.i
.PHONY : src/compiler/stmt.cpp.i

src/compiler/stmt.s: src/compiler/stmt.cpp.s
.PHONY : src/compiler/stmt.s

# target to generate assembly for a file
src/compiler/stmt.cpp.s:
	$(MAKE) -f CMakeFiles/p6.dir/build.make CMakeFiles/p6.dir/src/compiler/stmt.cpp.s
.PHONY : src/compiler/stmt.cpp.s

src/compiler/sub.o: src/compiler/sub.cpp.o
.PHONY : src/compiler/sub.o

# target to build an object file
src/compiler/sub.cpp.o:
	$(MAKE) -f CMakeFiles/p6.dir/build.make CMakeFiles/p6.dir/src/compiler/sub.cpp.o
.PHONY : src/compiler/sub.cpp.o

src/compiler/sub.i: src/compiler/sub.cpp.i
.PHONY : src/compiler/sub.i

# target to preprocess a source file
src/compiler/sub.cpp.i:
	$(MAKE) -f CMakeFiles/p6.dir/build.make CMakeFiles/p6.dir/src/compiler/sub.cpp.i
.PHONY : src/compiler/sub.cpp.i

src/compiler/sub.s: src/compiler/sub.cpp.s
.PHONY : src/compiler/sub.s

# target to generate assembly for a file
src/compiler/sub.cpp.s:
	$(MAKE) -f CMakeFiles/p6.dir/build.make CMakeFiles/p6.dir/src/compiler/sub.cpp.s
.PHONY : src/compiler/sub.cpp.s

src/linker/executable.o: src/linker/executable.cpp.o
.PHONY : src/linker/executable.o

# target to build an object file
src/linker/executable.cpp.o:
	$(MAKE) -f CMakeFiles/p6.dir/build.make CMakeFiles/p6.dir/src/linker/executable.cpp.o
.PHONY : src/linker/executable.cpp.o

src/linker/executable.i: src/linker/executable.cpp.i
.PHONY : src/linker/executable.i

# target to preprocess a source file
src/linker/executable.cpp.i:
	$(MAKE) -f CMakeFiles/p6.dir/build.make CMakeFiles/p6.dir/src/linker/executable.cpp.i
.PHONY : src/linker/executable.cpp.i

src/linker/executable.s: src/linker/executable.cpp.s
.PHONY : src/linker/executable.s

# target to generate assembly for a file
src/linker/executable.cpp.s:
	$(MAKE) -f CMakeFiles/p6.dir/build.make CMakeFiles/p6.dir/src/linker/executable.cpp.s
.PHONY : src/linker/executable.cpp.s

src/linker/linker.o: src/linker/linker.cpp.o
.PHONY : src/linker/linker.o

# target to build an object file
src/linker/linker.cpp.o:
	$(MAKE) -f CMakeFiles/p6.dir/build.make CMakeFiles/p6.dir/src/linker/linker.cpp.o
.PHONY : src/linker/linker.cpp.o

src/linker/linker.i: src/linker/linker.cpp.i
.PHONY : src/linker/linker.i

# target to preprocess a source file
src/linker/linker.cpp.i:
	$(MAKE) -f CMakeFiles/p6.dir/build.make CMakeFiles/p6.dir/src/linker/linker.cpp.i
.PHONY : src/linker/linker.cpp.i

src/linker/linker.s: src/linker/linker.cpp.s
.PHONY : src/linker/linker.s

# target to generate assembly for a file
src/linker/linker.cpp.s:
	$(MAKE) -f CMakeFiles/p6.dir/build.make CMakeFiles/p6.dir/src/linker/linker.cpp.s
.PHONY : src/linker/linker.cpp.s

src/linker/module.o: src/linker/module.cpp.o
.PHONY : src/linker/module.o

# target to build an object file
src/linker/module.cpp.o:
	$(MAKE) -f CMakeFiles/p6.dir/build.make CMakeFiles/p6.dir/src/linker/module.cpp.o
.PHONY : src/linker/module.cpp.o

src/linker/module.i: src/linker/module.cpp.i
.PHONY : src/linker/module.i

# target to preprocess a source file
src/linker/module.cpp.i:
	$(MAKE) -f CMakeFiles/p6.dir/build.make CMakeFiles/p6.dir/src/linker/module.cpp.i
.PHONY : src/linker/module.cpp.i

src/linker/module.s: src/linker/module.cpp.s
.PHONY : src/linker/module.s

# target to generate assembly for a file
src/linker/module.cpp.s:
	$(MAKE) -f CMakeFiles/p6.dir/build.make CMakeFiles/p6.dir/src/linker/module.cpp.s
.PHONY : src/linker/module.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/p6.dir/build.make CMakeFiles/p6.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/p6.dir/build.make CMakeFiles/p6.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/p6.dir/build.make CMakeFiles/p6.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/parser/ast.o: src/parser/ast.cpp.o
.PHONY : src/parser/ast.o

# target to build an object file
src/parser/ast.cpp.o:
	$(MAKE) -f CMakeFiles/p6.dir/build.make CMakeFiles/p6.dir/src/parser/ast.cpp.o
.PHONY : src/parser/ast.cpp.o

src/parser/ast.i: src/parser/ast.cpp.i
.PHONY : src/parser/ast.i

# target to preprocess a source file
src/parser/ast.cpp.i:
	$(MAKE) -f CMakeFiles/p6.dir/build.make CMakeFiles/p6.dir/src/parser/ast.cpp.i
.PHONY : src/parser/ast.cpp.i

src/parser/ast.s: src/parser/ast.cpp.s
.PHONY : src/parser/ast.s

# target to generate assembly for a file
src/parser/ast.cpp.s:
	$(MAKE) -f CMakeFiles/p6.dir/build.make CMakeFiles/p6.dir/src/parser/ast.cpp.s
.PHONY : src/parser/ast.cpp.s

src/parser/lexer.o: src/parser/lexer.cpp.o
.PHONY : src/parser/lexer.o

# target to build an object file
src/parser/lexer.cpp.o:
	$(MAKE) -f CMakeFiles/p6.dir/build.make CMakeFiles/p6.dir/src/parser/lexer.cpp.o
.PHONY : src/parser/lexer.cpp.o

src/parser/lexer.i: src/parser/lexer.cpp.i
.PHONY : src/parser/lexer.i

# target to preprocess a source file
src/parser/lexer.cpp.i:
	$(MAKE) -f CMakeFiles/p6.dir/build.make CMakeFiles/p6.dir/src/parser/lexer.cpp.i
.PHONY : src/parser/lexer.cpp.i

src/parser/lexer.s: src/parser/lexer.cpp.s
.PHONY : src/parser/lexer.s

# target to generate assembly for a file
src/parser/lexer.cpp.s:
	$(MAKE) -f CMakeFiles/p6.dir/build.make CMakeFiles/p6.dir/src/parser/lexer.cpp.s
.PHONY : src/parser/lexer.cpp.s

src/parser/parser.o: src/parser/parser.cpp.o
.PHONY : src/parser/parser.o

# target to build an object file
src/parser/parser.cpp.o:
	$(MAKE) -f CMakeFiles/p6.dir/build.make CMakeFiles/p6.dir/src/parser/parser.cpp.o
.PHONY : src/parser/parser.cpp.o

src/parser/parser.i: src/parser/parser.cpp.i
.PHONY : src/parser/parser.i

# target to preprocess a source file
src/parser/parser.cpp.i:
	$(MAKE) -f CMakeFiles/p6.dir/build.make CMakeFiles/p6.dir/src/parser/parser.cpp.i
.PHONY : src/parser/parser.cpp.i

src/parser/parser.s: src/parser/parser.cpp.s
.PHONY : src/parser/parser.s

# target to generate assembly for a file
src/parser/parser.cpp.s:
	$(MAKE) -f CMakeFiles/p6.dir/build.make CMakeFiles/p6.dir/src/parser/parser.cpp.s
.PHONY : src/parser/parser.cpp.s

src/runtime/gc.o: src/runtime/gc.cpp.o
.PHONY : src/runtime/gc.o

# target to build an object file
src/runtime/gc.cpp.o:
	$(MAKE) -f CMakeFiles/p6.dir/build.make CMakeFiles/p6.dir/src/runtime/gc.cpp.o
.PHONY : src/runtime/gc.cpp.o

src/runtime/gc.i: src/runtime/gc.cpp.i
.PHONY : src/runtime/gc.i

# target to preprocess a source file
src/runtime/gc.cpp.i:
	$(MAKE) -f CMakeFiles/p6.dir/build.make CMakeFiles/p6.dir/src/runtime/gc.cpp.i
.PHONY : src/runtime/gc.cpp.i

src/runtime/gc.s: src/runtime/gc.cpp.s
.PHONY : src/runtime/gc.s

# target to generate assembly for a file
src/runtime/gc.cpp.s:
	$(MAKE) -f CMakeFiles/p6.dir/build.make CMakeFiles/p6.dir/src/runtime/gc.cpp.s
.PHONY : src/runtime/gc.cpp.s

src/runtime/value.o: src/runtime/value.cpp.o
.PHONY : src/runtime/value.o

# target to build an object file
src/runtime/value.cpp.o:
	$(MAKE) -f CMakeFiles/p6.dir/build.make CMakeFiles/p6.dir/src/runtime/value.cpp.o
.PHONY : src/runtime/value.cpp.o

src/runtime/value.i: src/runtime/value.cpp.i
.PHONY : src/runtime/value.i

# target to preprocess a source file
src/runtime/value.cpp.i:
	$(MAKE) -f CMakeFiles/p6.dir/build.make CMakeFiles/p6.dir/src/runtime/value.cpp.i
.PHONY : src/runtime/value.cpp.i

src/runtime/value.s: src/runtime/value.cpp.s
.PHONY : src/runtime/value.s

# target to generate assembly for a file
src/runtime/value.cpp.s:
	$(MAKE) -f CMakeFiles/p6.dir/build.make CMakeFiles/p6.dir/src/runtime/value.cpp.s
.PHONY : src/runtime/value.cpp.s

src/runtime/vm.o: src/runtime/vm.cpp.o
.PHONY : src/runtime/vm.o

# target to build an object file
src/runtime/vm.cpp.o:
	$(MAKE) -f CMakeFiles/p6.dir/build.make CMakeFiles/p6.dir/src/runtime/vm.cpp.o
.PHONY : src/runtime/vm.cpp.o

src/runtime/vm.i: src/runtime/vm.cpp.i
.PHONY : src/runtime/vm.i

# target to preprocess a source file
src/runtime/vm.cpp.i:
	$(MAKE) -f CMakeFiles/p6.dir/build.make CMakeFiles/p6.dir/src/runtime/vm.cpp.i
.PHONY : src/runtime/vm.cpp.i

src/runtime/vm.s: src/runtime/vm.cpp.s
.PHONY : src/runtime/vm.s

# target to generate assembly for a file
src/runtime/vm.cpp.s:
	$(MAKE) -f CMakeFiles/p6.dir/build.make CMakeFiles/p6.dir/src/runtime/vm.cpp.s
.PHONY : src/runtime/vm.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... p6"
	@echo "... rebuild_cache"
	@echo "... src/common/byte_buffer.o"
	@echo "... src/common/byte_buffer.i"
	@echo "... src/common/byte_buffer.s"
	@echo "... src/common/errors.o"
	@echo "... src/common/errors.i"
	@echo "... src/common/errors.s"
	@echo "... src/common/utils.o"
	@echo "... src/common/utils.i"
	@echo "... src/common/utils.s"
	@echo "... src/compiler/assign.o"
	@echo "... src/compiler/assign.i"
	@echo "... src/compiler/assign.s"
	@echo "... src/compiler/codegen.o"
	@echo "... src/compiler/codegen.i"
	@echo "... src/compiler/codegen.s"
	@echo "... src/compiler/compiler.o"
	@echo "... src/compiler/compiler.i"
	@echo "... src/compiler/compiler.s"
	@echo "... src/compiler/expr.o"
	@echo "... src/compiler/expr.i"
	@echo "... src/compiler/expr.s"
	@echo "... src/compiler/frame.o"
	@echo "... src/compiler/frame.i"
	@echo "... src/compiler/frame.s"
	@echo "... src/compiler/package.o"
	@echo "... src/compiler/package.i"
	@echo "... src/compiler/package.s"
	@echo "... src/compiler/stmt.o"
	@echo "... src/compiler/stmt.i"
	@echo "... src/compiler/stmt.s"
	@echo "... src/compiler/sub.o"
	@echo "... src/compiler/sub.i"
	@echo "... src/compiler/sub.s"
	@echo "... src/linker/executable.o"
	@echo "... src/linker/executable.i"
	@echo "... src/linker/executable.s"
	@echo "... src/linker/linker.o"
	@echo "... src/linker/linker.i"
	@echo "... src/linker/linker.s"
	@echo "... src/linker/module.o"
	@echo "... src/linker/module.i"
	@echo "... src/linker/module.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/parser/ast.o"
	@echo "... src/parser/ast.i"
	@echo "... src/parser/ast.s"
	@echo "... src/parser/lexer.o"
	@echo "... src/parser/lexer.i"
	@echo "... src/parser/lexer.s"
	@echo "... src/parser/parser.o"
	@echo "... src/parser/parser.i"
	@echo "... src/parser/parser.s"
	@echo "... src/runtime/gc.o"
	@echo "... src/runtime/gc.i"
	@echo "... src/runtime/gc.s"
	@echo "... src/runtime/value.o"
	@echo "... src/runtime/value.i"
	@echo "... src/runtime/value.s"
	@echo "... src/runtime/vm.o"
	@echo "... src/runtime/vm.i"
	@echo "... src/runtime/vm.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

